### PR TITLE
fix: UserResponse can now be null

### PR DESCRIPTION
**Pull request by jonas-martinez**
## About this PR

Linked to https://github.com/lenra-io/server/issues/399

There was a problem when the access token was invalid where the server tried to get the user linked to this access token from the DB but because the access token is invalid, it returned `nil` instead of the user object. 

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [x] I made my own code-review before requesting one

### I included unit tests that cover my changes
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes
- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by taorepoara** [comment]
@jonas-martinez Can you explain this PR please ?

**Comment by jonas-martinez** [comment]
@taorepoara I added some context in the PR description

**Comment by taorepoara** [comment]
In my opinion this can't happen or it should return an error from the server.

**Comment by jonas-martinez** [comment]
@taorepoara I'm going to see if I can do something, I'm moving this PR to `In Progress`

**Comment by jonas-martinez** [comment]
This PR can be closed as an alternative has been found involving the server sending an error instead of nil.

**Pull request closed without merging**
